### ISSUE TITLE
Problem, when using the Labs, in real life

### ISSUE THREAD

**Issue by ClausSuperusers** [MicrosoftLearning/20483-Programming-in-C-Sharp#63]
I'm an MCT, instructing - among other - The 20483 Programming in C# Course.
I've been using self-developed Labs in the course, but thought I would give the official material a try after the recent update.

First, it is important to hold in mind, that the new Labs are required to run on a very mixed set of computers, each with their own level of updates and installed software.
I've tried using my own office/development computer and quickly ran into problems:

Database 1:

Creating a database, using then delivered script **SetupSchoolDB.cmd**, was impossible - Windows rejected this with a warning about dangerous software.

Database 2:

Instead I tried to execute the backing script (SchoolDB.sql) from a Query inside Visual Studio (Enterprise 2017, release 15.7.4). The result was multiple errors, mostly because the script tries to force the location and size of the database files.
A simple workaround is to delete the lines from the script, after witch the database gets created.
NOTE!
This creates the database on my default local server, which - as far as I know - was installed by Visual Studio. Target is simply: (localdb)\MSSQLLocalDB

Labs in Visual Studio 1:

When opening the first Lab, I am met by a message saying that the project requires .Net 4.7.
I've only got 4.6.1 - the dialog suggest downgrading the project to that version.
Do any of the labs actually require 4.7 or can an older version work?

Labs in Visual Studio 2:

Finally able to execute the application - hit F5 and we are up and running.
No. After a long time the form shows, but no data.
Investigation in the Config file shows, that the Connection String references ".\sqlexpress".
SQLexpress 2017 is actually one of the requirement in the setup guide for the Course, but why?
Changing the reference to "(localdb)\MSSQLLocalDB" makes everything run smoothly. . .

I haven't come any further in my experimenting with the labs.

Finally a comment with respect to the Labs. This is NOT directed at this course specifically, but more in general:
Our Students use more time, trying to understand the Application in general, actually working with code for the current subject is usually a very minor part of the time used.

**Comment by rofr** [comment]
@ClausSuperusers I forked the repo and fixed these issues (except the 4.7) stuff...
https://github.com/rofr/20483-Programming-in-C-Sharp
All connection strings in all config files now point at (localdb)\MSSQLLocalDB, paths have been removed from sql files and CMD files were removed completely (no point in having them unless sqlcmd.exe exists

**Comment by Divan5011** [comment]
For the .Net 4.7... This file might be installed on your computer but not in your Visual Studio.. There go to your Visual Studio Installer...  Windows Start Menu >> Visual Studio Installer >> and Open...   
When Application is Open Click on Modify Under Installed.. Once you clicked on modify find in the Tabs "Individual Components. Then Scroll through and check the " >NET Framework 4.7 targeting pack".  Now click modify at bottom right.  Make sure the actual Visual Studio is not running. Boom Now open your solution and you will find the problem doesn't exists anymore. If so follow this link..    https://youtu.be/YIdOBwHGAp4

**Comment by Prace** [comment]
> Finally a comment with respect to the Labs. This is NOT directed at this course specifically, but more in general: Our Students use more time, trying to understand the Application in general, actually working with code for the current subject is usually a very minor part of the time used.

This. I don't have a strong WPF background, since I've been mainly developing C# for Web applications and little to none desktop UIs. Although I understand the rationale behind the whole desktop application flow, for these exercises I often find myself wondering how to implement even basic interfaces, while the main focus of the task should be another, e.g. using some LINQ queries. 

I think that examples for this course should be straightforward console applications with focus on the feature of C# that is being studied, rather than a fully-fledged desktop UI application with Entity Framework, (especially when the teacher is explaining basic for and while loops during the lesson).

**Comment by ChRocheFR** [comment]
> I think that examples for this course should be straightforward console applications with focus on the feature of C# that is being studied, rather than a fully-fledged desktop UI application with Entity Framework, (_especially when the teacher is explaining basic for and while loops during the lesson_).

I agree with the complexity of the application, but those who attend this course should already know the concepts of the first modules. As it is said, they must have significant experience in C++, Java, Objective C...

**Comment by ChrisBarkerMCT** [comment]
If you want a course that focuses on C# as a language, I published one about 2 years ago using VS2017 community edition. Any trainer can teach it, and trainers may also request a free copy of the course in Skillpipe. There is a link to the Arvato home page for the course from my web site: [Courses](http://charliebravotango.com/Home/Courses). If you want any further information, including how to get a preview look at the course (and quite a few others (by different authors)) let me know: chris@charliebravotango.com

**Comment by Prace** [comment]
> > I think that examples for this course should be straightforward console applications with focus on the feature of C# that is being studied, rather than a fully-fledged desktop UI application with Entity Framework, (_especially when the teacher is explaining basic for and while loops during the lesson_).
> 
> I agree with the complexity of the application, but those who attend this course should already know the concepts of the first modules. As it is said, they must have significant experience in C++, Java, Objective C...

I'm not complaining about operators and flow control, because those are tools that every depelover needs to understand perfectly and should use everyday. What I'm saying is that if you want to highlight the differences from - say - a for loop in Ruby, a class in Python, a Java inteface, or just showing some particular features of the C# language, you do not need to implement a complete application that makes use of overly complicated frameworks that are not in the actual exam.

As a developer myself (MCSA and MCSD in 2 days, to be precise), I would prefer a simple console application that I can play with, rather than scratching my head on EF exceptions when I run an example aimed at showing a Linq query.
